# Generated by Django 4.2.9 on 2024-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
